[package]
name = "rusty_music"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mp3-duration = "0.1.10"
notify-rust = "4.8.0"
rodio = "0.17.0"
