[package]
name = "music_player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html 69

[dependencies]
lofty = "0.11.0"
notify-rust = "4.8.0"
rodio = "0.17.1"
walkdir = "2.3.2"
