[package]
name = "player"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html 69

[dependencies]
glob = "0.3.1"
rodio = "0.16.0"
lofty = "0.11.0"
console = "0.15.7"
